# SPDX-FileCopyrightText: 2021 Melissa LeBlanc-Williams for Adafruit Industries
#
# SPDX-License-Identifier: Unlicense

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
